### PR TITLE
update route

### PR DESCRIPTION
**Pull request by rajivharlalka**
This PR contains two endpoints, one for getting the Project details and the other for updating the details.
- desc
- tags
- branch
These fields will be available for update, and so these data are only pulled from the db in the getProject endpoint.

The return of this endpoint is a json which will be of a form somewhat this
```json
{
 "branch":"",
 "desc":"gvgb",
 "name":"de",
 "tags":"[\"python3\",\"python\",\"cli\",\"website\",\"todo\",\"todoapp\",\"easy-to-use\",\"pip\",\"makefile\"]"
}
```

### CODE REVIEW

**Comment by rajivharlalka** [comment]
Fixes #42

**Comment by rajivharlalka** [comment]
Currently the update route searches the project table with the name of project and updates for  description, tags and branch is available (subject to change).

**Comment by rajivharlalka** [comment]
Checks passing 😄

**Comment by sahil-shubham** [comment]
To whoever is going to merge this PR - squash and merge.

**Pull request merged**
