### PR TITLE
Fixed Multiple Registrations Bug

### LINKED ISSUE #95: Multiple login sessions are considered as new entries in table
If the user say, logins into multiple devices or doesn't stores cookies and logins multiple times then each event is considered a new entry into db, bloating it unnecessarily.

### PR DESCRIPTION
**Pull request by harshkhandeparkar**
Closes #95

#### Changes
- Added a check in mentor and student controllers for existing entries and return an error to prevent multiple registrations.

### CODE REVIEW

**Review by proffapt — COMMENTED** [review]
Logically seems good, have you tested it in production?

**Review by rajivharlalka — COMMENTED** [review]
LGTM, though can you test it once on some demo data

**Comment by harshkhandeparkar** [comment]
I have tested it locally.

**Comment by harshkhandeparkar** [comment]
> Logically seems good, have you tested it in production?

Tested it on devDB

**Review by proffapt — APPROVED** [review]
LGTM, then

**Review by rajivharlalka — APPROVED** [review]

**Pull request merged**
